version: '3'

services:
  influxdb:
    image: influxdb:1.2.2
    ports:
      - "25826:25826/udp"
      - "8086:8086"
    volumes:
      - influxdb-volume:/var/lib/influxdb
      - ./influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
      - ./influxdb/types.db:/etc/influxdb/types.db:ro
    networks:
      - internal-bridge
  grafana:
    image: grafana/grafana:4.2.0
    environment:
      GF_SERVER_PROTOCOL: "http"
      GF_SERVER_ROOT_URL: "%(protocol)s://%(domain)s:/grafana"
      GF_SERVER_DOMAIN: "${GF_SERVER_DOMAIN}"
    ports:
      - "3000:3000"
    volumes:
      - grafana-volume:/var/lib/grafana
    networks:
      - internal-bridge

volumes:
  influxdb-volume:
  grafana-volume:

networks:
  internal-bridge:
