version: '3'

services:
  influxdb:
    image: influxdb:1.2.2-alpine
    ports:
      - "8086:8086"
    volumes:
      - influxdb-volume:/var/lib/influxdb
    networks:
      - collection-group-network
    logging:
      driver: syslog
      options:
        syslog-address: "${SYSLOG_ADDRESS}"
  grafana:
    image: grafana/grafana:4.2.0
    environment:
      GF_SERVER_PROTOCOL: "http"
      GF_SERVER_ROOT_URL: "%(protocol)s://%(domain)s:/grafana"
      GF_SERVER_DOMAIN: "${GF_SERVER_DOMAIN}"
    ports:
      - "3000:3000"
    volumes:
      - grafana-volume:/var/lib/grafana
    networks:
      - collection-group-network
    logging:
      driver: syslog
      options:
        syslog-address: "${SYSLOG_ADDRESS}"

volumes:
  influxdb-volume:
  grafana-volume:

networks:
  collection-group-network:
